[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "filestore"
version = "1.0.7"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ['fastapi', 'filestorage', 'cloudstorage', 'storageengine', 'filestore']
authors = [{name = "Ichinga Samuel", email = "ichingasamuel@gmail.com"}]
description = "Storage Engine Package for FastAPI"
dependencies = [
    "fastapi",
    "python-multipart",
]
[project.optional-dependencies]
s3 = [
    'boto3',
]

[project.urls]
"Homepage" = "https://github.com/Ichinga-Samuel/faststore"
"Bug Tracker" = "https://github.com/Ichinga-Samuel/faststore/issues"